// Datos de proyectos de muestra (falsos) compartidos entre resultados.html
// y proyecto.html para esta versión preliminar de FUTURA.
window.FUTURA_PROJECTS = [
  {
    id: "vista-alta-escazu",
    name: "Vista Alta Escazú",
    zone: "Escazú, San José",
    location: { lat: 9.9189, lng: -84.1439 },
    priceFrom: 185000,
    bedrooms: "2–3 hab.",
    delivery: "2027",
    amenities: ["Piscina", "Gimnasio", "Coworking", "Seguridad 24/7"],
    developer: { name: "Grupo Terra Nova", slug: "grupo-terra-nova" },
    typologies: [
      { id: "a", name: "Tipo A", sqm: 62, bedrooms: 2, bathrooms: 2 },
      { id: "b", name: "Tipo B", sqm: 88, bedrooms: 3, bathrooms: 2.5 },
    ],
  },
  {
    id: "bosques-santa-ana",
    name: "Bosques de Santa Ana",
    zone: "Santa Ana, San José",
    location: { lat: 9.9281, lng: -84.183 },
    priceFrom: 265000,
    bedrooms: "3–4 hab.",
    delivery: "2026",
    amenities: ["Áreas verdes", "Piscina", "Salón de eventos", "Cancha multiuso"],
    developer: { name: "Inversiones Cerro Alto", slug: "inversiones-cerro-alto" },
    typologies: [
      { id: "a", name: "Tipo A", sqm: 110, bedrooms: 3, bathrooms: 3 },
      { id: "b", name: "Tipo B", sqm: 145, bedrooms: 4, bathrooms: 3.5 },
    ],
  },
  {
    id: "terrazas-curridabat",
    name: "Terrazas Curridabat",
    zone: "Curridabat, San José",
    location: { lat: 9.9167, lng: -84.0333 },
    priceFrom: 210000,
    bedrooms: "2 hab.",
    delivery: "2027",
    amenities: ["Rooftop", "Gimnasio", "Pet-friendly", "Coworking"],
    developer: { name: "Constructora Volcán", slug: "constructora-volcan" },
    typologies: [
      { id: "a", name: "Tipo A", sqm: 58, bedrooms: 2, bathrooms: 1 },
      { id: "b", name: "Tipo B", sqm: 68, bedrooms: 2, bathrooms: 2 },
    ],
  },
  {
    id: "alto-heredia",
    name: "Alto Heredia",
    zone: "Heredia centro",
    location: { lat: 10.0, lng: -84.1165 },
    priceFrom: 195000,
    bedrooms: "3 hab.",
    delivery: "2026",
    amenities: ["Piscina", "Parque infantil", "Seguridad 24/7"],
    developer: { name: "Desarrollos Montebello", slug: "desarrollos-montebello" },
    typologies: [
      { id: "a", name: "Tipo A", sqm: 95, bedrooms: 3, bathrooms: 2 },
      { id: "b", name: "Tipo B", sqm: 105, bedrooms: 3, bathrooms: 2.5 },
    ],
  },
  {
    id: "cerro-verde",
    name: "Cerro Verde Concepción",
    zone: "San Rafael de Escazú",
    location: { lat: 9.937, lng: -84.152 },
    priceFrom: 340000,
    bedrooms: "4 hab.",
    delivery: "2028",
    amenities: ["Club house", "Piscina infinita", "Gimnasio", "Senderos naturales"],
    developer: { name: "Altura Desarrollos", slug: "altura-desarrollos" },
    typologies: [
      { id: "a", name: "Tipo A", sqm: 165, bedrooms: 4, bathrooms: 3.5 },
      { id: "b", name: "Penthouse", sqm: 210, bedrooms: 4, bathrooms: 4.5 },
    ],
  },
];
